docker:
    path: .
id: 96de36bb-2825-448d-be13-8f59514a03a9
ide:
    filename: ide.yaml
name: agent-skills-workshop
resources:
    path: resources
streaming:
    filename: streaming.yaml
template: ""
version: "0.3"
workflows:
    path: exercises/data-engineer/demo/dags
    version: "3"
