docker:
    path: "."
name: agent-skills-workshop
id: bd05a656-6645-4468-bdd0-53a67731bd57
ide:
    filename: ide.yaml
resources:
    path: resources
streaming:
    filename: streaming.yaml
template: ""
version: "0.3"
workflows:
    path: dags
    version: 2
